export type { IAnuncioRepository, AnuncioStats, NearbyAdResult, TopProdutoData } from './i-anuncio-repository';
export { ANUNCIO_REPOSITORY } from './i-anuncio-repository';
export type { ILojaRepository } from './i-loja-repository';
export { LOJA_REPOSITORY } from './i-loja-repository';
export type { IUsuarioRepository, RegistroUsuarioPorDia } from './i-usuario-repository';
export { USUARIO_REPOSITORY } from './i-usuario-repository';
export type { IProdutoRepository, PrecoHistoricoData } from './i-produto-repository';
export { PRODUTO_REPOSITORY } from './i-produto-repository';
export type { IFuncionarioLojaRepository } from './i-funcionario-loja-repository';
export { FUNCIONARIO_LOJA_REPOSITORY } from './i-funcionario-loja-repository';
